name: 🐞 Bug Report
description: Report a reproducible bug in Pexelle Market
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Read before submitting**

        This form is for **real, reproducible bugs only**.
        - No opinions
        - No feature requests
        - No security exploits (see security policy)

  # Title is handled by GitHub itself (Add a title *)

  - type: input
    id: scenario
    attributes:
      label: Related Test Scenario (if any)
      description: Reference a scenario from TEST_SCENARIOS.md
      placeholder: "e.g. QR Replay Attack"
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      options:
        - Identity / Authentication
        - Evidence Integrity
        - Skill & Evidence Mapping
        - Job Matching
        - AI Roadmap Generation
        - Market Analytics
        - UX / Trust Communication
        - Performance / Scalability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is broken?
      placeholder: |
        What is happening?
        Which part of the system is affected?
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      options:
        - 🟢 Informational
        - 🟡 Low
        - 🟠 Medium
        - 🔴 High
        - 🚨 Critical
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs, screenshots, recordings, traces, etc. (strongly recommended)
      placeholder: |
        Paste logs or attach files if available.
    validations:
      required: false

  - type: textarea
    id: analysis
    attributes:
      label: Technical Analysis (Optional but Strongly Encouraged)
      description: Why do you think this happens?
      placeholder: |
        Possible root cause
        Design vs implementation issue
    validations:
      required: false
