name: 💡 Feature / Improvement
description: Propose a feature or improvement for Pexelle Market
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Read before submitting**

        This is for **concrete, actionable features**.
        - No vague ideas
        - No “it would be cool if…”
        - No roadmap demands

  # Title is handled by GitHub (Add a title *)

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Identity / Authentication
        - Evidence Integrity
        - Skill & Evidence Mapping
        - Job Matching
        - AI Roadmap Generation
        - Market Analytics
        - UX / Trust Communication
        - Performance / Scalability
        - Developer Experience / Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        What is the pain?
        Who is affected?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What do you propose to add or change?
      placeholder: |
        Describe the solution briefly.
        High-level is fine.
    validations:
      required: true
