name: 🧪 Test Result / Finding
description: Report adversarial test results, suspicious behavior, or trust-related findings (not necessarily confirmed bugs yet)
title: "[TEST] "
labels: ["test-finding", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Read before submitting**
        
        Use this for **testing findings** and adversarial validation:
        - You tested a scenario and found unexpected behavior
        - You suspect a design flaw or trust break
        - You observed inconsistent verification or matching
        
        If your finding is fully reproducible and clearly a defect, you may still file a Bug Report —  
        but this template is preferred for **trust-related and adversarial** findings.

        🚨 **Security vulnerabilities must be reported privately** (see SECURITY policy). Do not post exploit details here.

  - type: input
    id: scenario
    attributes:
      label: Test Scenario Name / ID
      description: Reference TEST_SCENARIOS.md or describe your own scenario.
      placeholder: "Example: QR Replay Attack / Evidence Replacement Attempt"

  - type: dropdown
    id: area
    attributes:
      label: Area / Flow Tested
      options:
        - QR Auth / Account Linking
        - Evidence Upload / Verification
        - Evidence Immutability / Integrity
        - Skill Claims & Evidence Mapping
        - Dynamic Resume / Employer View
        - Job Matching / Ranking
        - AI Roadmap Generation
        - Market Analytics / Trends
        - UX / Trust Communication
        - Other
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What exactly were you trying to validate or break?
      placeholder: "Example: Validate whether QR tokens are single-use and bound to device/session."

  - type: dropdown
    id: severity
    attributes:
      label: Severity / Trust Impact
      options:
        - 🟢 Informational (interesting but no impact)
        - 🟡 Low (minor trust/UX confusion)
        - 🟠 Medium (could mislead employers/users)
        - 🔴 High (breaks trust guarantees)
        - 🚨 Critical (integrity/identity compromise suspected)
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs, screenshots, recordings, traces, request ids, hashes. No evidence = no triage.
      placeholder: |
        - Screenshots / recordings:
        - Console logs:
        - Network traces / HAR:
        - Request IDs / timestamps:
        - Transaction hashes (if relevant):

  - type: textarea
    id: analysis
    attributes:
      label: Analysis / Hypothesis (Optional but Valued)
      description: Your technical reasoning about why this might happen.
      placeholder: |
        Possible root cause:
        Trust boundary involved:
        Design flaw vs implementation bug:
